import type { ExamCategory, AcademicService } from "./defination";

export const examAidCategories: ExamCategory = {
  "Certification Exams": [
    "Microsoft Azure",
    "Google Cloud",
    "Cisco - CCNA/CCNP/CCIE",
    "ITIL",
    "Prince2 (Foundation & Practitioner)",
    "PMI-PMP",
    "PMI-ACP",
    "PMI-RMP",
    "CAPM",
    "CISA",
    "CISM",
    "CEH",
    "CRISC",
    "AWS Solution Architect Professional",
    "CompTIA Security+",
    "CompTIA Network+",
    "CompTIA A+",
    "Cybersecurity Analyst",
    "Pentest+",
    "Terraform",
    "Oracle",
  ],
  "College Level": [
    "DAT",
    "OAT",
    "MCAT",
    "GRE",
    "GED",
    "LSAT",
    "GMAT",
    "PCAT",
    "NCLEX",
    "TOEFL",
    "TEAS",
    "Medical Coding",
    "HesiPn",
    "Series 7",
    "CLEP",
    "CLEID",
    "ACUPLACER",
  ],
  "Grades K-12": ["ACT", "SAT", "AP", "PSAT", "SSAT", "ISEE", "HSPT"],
};

export const testPrepCategories: ExamCategory = {
  "Grades K-8": ["MAP", "TAKS", "AIMS"],
  "Grades 9-12": ["SAT", "PSAT", "ACT", "AP", "SSAT", "ISEE", "HSPT", "GED"],
  Graduate: [
    "DAT",
    "OAT",
    "MCAT",
    "LSAT",
    "GMAT",
    "GRE",
    "PCAT",
    "CLEP",
    "CLEID",
    "ACUPLACER",
    "NCLEX",
    "TOEFL",
    "TEAS",
    "Medical Coding",
    "HesiPn",
    "Series 7",
  ],
};

export const academicServices: AcademicService[] = [
  { name: "Assignment Help", href: "/academic/assignment-help" },
  { name: "Online Tutoring Services", href: "/academic/online-tutoring" },
  { name: "Class Assistant", href: "/academic/class-assistant" },
];

export const gradeLevels = [
  { name: "1st Grade Tutoring" },
  { name: "2nd Grade Tutoring" },
  { name: "3rd Grade Tutoring" },
  { name: "4th Grade Tutoring" },
  { name: "5th Grade Tutoring" },
  { name: "7th Grade Tutoring" },
  { name: "8th Grade Tutoring" },
  { name: "High School Tutoring" },
  { name: "College Tutoring" },
  { name: "Skills Based Tutoring" },
];

export const certifications = [
  { name: "Microsoft Azure", slug: "exam-aid/microsoft-azure" },
  {
    name: "AWS Solution Architect Professional",
    slug: "exam-aid/aws-solution-architect",
  },
  {
    name: "CompTIA Advanced Security Practitioner",
    slug: "exam-aid/comptia-asp",
  },
  { name: "Google Cloud", slug: "exam-aid/google-cloud" },
  { name: "CompTIA Security+", slug: "exam-aid/comptia-security-plus" },
  { name: "Cisco-CCNA/CCNP", slug: "exam-aid/cisco-ccna-ccnp" },
  { name: "CompTIA Network+", slug: "exam-aid/comptia-network-plus" },
  { name: "CompTIA Pentest+", slug: "exam-aid/comptia-pentest-plus" },
  {
    name: "ITIL, Prince2(Foundation & practitioner)",
    slug: "exam-aid/itil-prince2",
  },
  { name: "CompTIA A+", slug: "exam-aid/comptia-a-plus" },
  { name: "ISTOB", slug: "exam-aid/istob" },
  {
    name: "PMI-PMP, PMI-ACP, PMI-RMP, CAPM",
    slug: "exam-aid/pmi-certifications",
  },
  {
    name: "CompTIA Cybersecurity Analyst",
    slug: "exam-aid/comptia-cybersecurity-analyst",
  },
  { name: "Oracle", slug: "exam-aid/oracle" },
  { name: "CISA, CISM, CEH, CRISC", slug: "exam-aid/security-certifications" },
  { name: "Snowflake", slug: "exam-aid/snowflake" },
  { name: "Power BI", slug: "exam-aid/power-bi" },
  { name: "Terraform", slug: "exam-aid/terraform" },
];

export const tutorSubjects = [
  "ACT Tutors",
  "GMAT Tutors",
  "Pre-Calculus Tutors",
  "AP Tutors",
  "Grammar Tutors",
  "PSAT Tutors",
  "Calculus Tutors",
  "GRE Tutors",
  "Python Tutors",
  "Biology Tutors",
  "ISEE Tutors",
  "Real Estate Tutors",
  "Chemistry Tutors",
  "LSAT Tutors",
  "Reading Tutors",
  "Coding Tutors",
  "MCAT Tutors",
  "SAT Math Tutors",
  "Geometry Tutors",
  "Math Tutors",
  "SSAT Tutors",
  "Elementary Tutors",
  "NCLEX Tutors",
  "Writing Tutors",
  "Nursing Tutors",
  "Physics Tutors",
  "Test Prep Tutors",
];

export const testPrepSubjects = [
  { name: "ACT", slug: "test-prep/act" },
  { name: "GRE", slug: "test-prep/gre" },
  { name: "ADAT", slug: "test-prep/adat" },
  { name: "AP", slug: "test-prep/ap" },
  { name: "GMAT", slug: "test-prep/gmat" },
  { name: "ISEE", slug: "test-prep/isee" },
  { name: "MAP", slug: "test-prep/map" },
  { name: "LSAT", slug: "test-prep/lsat" },
  { name: "Acuplacer", slug: "test-prep/acuplacer" },
  { name: "PARCC", slug: "test-prep/parcc" },
  { name: "MCAT", slug: "test-prep/mcat" },
  { name: "HSPT", slug: "test-prep/hspt" },
  { name: "PSAT", slug: "test-prep/psat" },
  { name: "TOEFL", slug: "test-prep/toefl" },
  { name: "MTTLE", slug: "test-prep/mttle" },
  { name: "NMSQT", slug: "test-prep/nmsqt" },
  { name: "BTECs", slug: "test-prep/btecs" },
  { name: "Series", slug: "test-prep/series" },
  { name: "SAT", slug: "test-prep/sat" },
  { name: "UKCAT", slug: "test-prep/ukcat" },
  { name: "7,3,6,63,65,66", slug: "test-prep/7-3-6-63-65-66" },
  { name: "IB", slug: "test-prep/ib" },
  { name: "BMAT", slug: "test-prep/bmat" },
  { name: "CCNA", slug: "test-prep/ccna" },
  { name: "ComTIA", slug: "test-prep/comtia" },
  { name: "TEAS", slug: "test-prep/teas" },
  { name: "HesiPN", slug: "test-prep/hesipn" },
  { name: "AttTeas", slug: "test-prep/attteas" },
  { name: "GED", slug: "test-prep/ged" },
  { name: "SIE", slug: "test-prep/sie" },
];
