import type { ExamCategory, AcademicService } from "./defination";

export const examAidCategories: ExamCategory = {
  "Certification Exams": [
    "Microsoft Azure",
    "Google Cloud",
    "Cisco - CCNA/CCNP/CCIE",
    "ITIL",
    "Prince2 (Foundation & Practitioner)",
    "PMI-PMP",
    "PMI-ACP",
    "PMI-RMP",
    "CAPM",
    "CISA",
    "CISM",
    "CEH",
    "CRISC",
    "AWS Solution Architect Professional",
    "CompTIA Security+",
    "CompTIA Network+",
    "CompTIA A+",
    "Cybersecurity Analyst",
    "Pentest+",
    "Terraform",
    "Oracle",
  ],
  "College Level": [
    "DAT",
    "OAT",
    "MCAT",
    "GRE",
    "GED",
    "LSAT",
    "GMAT",
    "PCAT",
    "NCLEX",
    "TOEFL",
    "TEAS",
    "Medical Coding",
    "HesiPn",
    "Series 7",
    "CLEP",
    "CLEID",
    "ACUPLACER",
  ],
  "Grades K-12": ["ACT", "SAT", "AP", "PSAT", "SSAT", "ISEE", "HSPT"],
};

export const testPrepCategories: ExamCategory = {
  "Grades K-8": ["MAP", "TAKS", "AIMS"],
  "Grades 9-12": ["SAT", "PSAT", "ACT", "AP", "SSAT", "ISEE", "HSPT", "GED"],
  Graduate: [
    "DAT",
    "OAT",
    "MCAT",
    "LSAT",
    "GMAT",
    "GRE",
    "PCAT",
    "CLEP",
    "CLEID",
    "ACUPLACER",
    "NCLEX",
    "TOEFL",
    "TEAS",
    "Medical Coding",
    "HesiPn",
    "Series 7",
  ],
};

export const academicServices: AcademicService[] = [
  { name: "Assignment Help", href: "/academic/assignment-help" },
  { name: "Online Tutoring Services", href: "/academic/online-tutoring" },
  { name: "Class Assistant", href: "/academic/class-assistant" },
];
